trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Perform Build"

- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Deploy at Dev Env
    
- stage: QaDeploy
  jobs:
  - deployment: QADeployJob
    environment: Qa
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Deploy at QA Envirment
